apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: appd-ktor-test
  namespace: default
  labels:
    team: medlemskap
spec:
  image: {{ image }}
  port: 7070
  liveness:
    path: isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isReady
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://appd-ktor-test.nais.preprod.local
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: APP_NAME
      value: "appd-ktor-test"
    - name: APP_VERSION
      value: "0.0.1"
    - name: APP_ENVIRONMENT
      value: "default"
